import { chromium } from 'playwright-core';
const browser = await chromium.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: true });
const page = await (await browser.newContext({ viewport: { width: 1200, height: 900 } })).newPage();
page.on('pageerror', (e) => console.log('PAGEERROR', e.message));
page.on('console', (m) => { if (m.type() === 'error') console.log('CONSOLE', m.text().slice(0, 300)); });
await page.goto('file://' + process.cwd() + '/zeus/anime/wheel.html');
await page.waitForTimeout(2500);
await page.screenshot({ path: 'zeus/anime/wheel-0.png', clip: { x: 0, y: 60, width: 700, height: 560 } });
await page.click('#spinBtn');
await page.waitForTimeout(600); await page.screenshot({ path: 'zeus/anime/wheel-1.png', clip: { x: 0, y: 60, width: 700, height: 560 } });
await page.waitForTimeout(4200); await page.screenshot({ path: 'zeus/anime/wheel-2.png', clip: { x: 0, y: 60, width: 700, height: 560 } });
console.log('wheel transform:', await page.$eval('[data-id="innerWheel"]', (e) => e.style.transform));
await browser.close();
